### PR TITLE
upgrade: vllm-tgis-adapter to 0.8.1

### PR DESCRIPTION
**Pull request by edwardquarm**
jira: https://issues.redhat.com/browse/RHOAIENG-35041 and https://issues.redhat.com/browse/RHOAIENG-35040

vllm-tgis-adapter is updated to 0.8.1 to work with vllm v0.10.0 (RHOAI 2.24). 
Fixes Lora adapter crash
``Inference on LoRA-tuned model fails with error: 'str' object has no attribute 'lora_name' ``

Also addresses https://issues.redhat.com/browse/INFERENG-2231

### CODE REVIEW

**Review by dtrifiro — APPROVED** [review]

**Review by dtrifiro — APPROVED** [review]

**Review by RH-steve-grubb — APPROVED** [review]

**Comment by edwardquarm** [comment]
closing PR as the Lora fix is not needed for 2.24
